### ISSUE TITLE
Problem with initial character position in canvas?

### ISSUE THREAD

**Issue by roschler** [aws-samples/amazon-sumerian-hosts#15]
I changed the three.html sample from using the Luke character over to Cristine.  That was the only change I made:
```
        // ROS: const characterFile1 = './assets/glTF/characters/adult_male/luke/luke.gltf';
        const characterFile1 =
          './assets/glTF/characters/adult_female/cristine/cristine.gltf';
```

For some odd reason, instead of appearing where Luke does on the canvas, she appears way off the screen in the far upper left corner of the coordinate space, far outside the visible viewport.  Looking at the code, I see this initialization Javascript:
```
        character1.position.set(1.25, 0, 0);
        character1.rotateY(-0.5);
```
Why does that code work properly for Luke but not Cristine?  I have no experience with glTF related files, so is there something in those files that could affect the way the position of one character would be effectively rendered compared to another?

Everything else works fine, and the Alien character even looks off into space at her current location when she's talking.  But as I said "she's out in the boonies".  I have to use the mouse wheel quite a bit to zoom the camera outwards to bring her into view.

Also, is there a Slack, forum, or IRC chat room for asking questions about this project?

**Comment by c-morten** [comment]
You'll need to change the animation path to point to the female folder rather than the male folder as well. I'm not entirely sure why that would result in the character moving way off the screen but you definitely want to point to the animation folder that matches the character skeleton category. Please post back if this fixes the problem and I'll close out the issue.

As for chat or forum, we don't have anything like that set up just yet. We're waiting a bit to see how much interest the repository gets.

**Comment by roschler** [comment]
@c-morten Thanks, I'll try that and report back.

**Comment by roschler** [comment]
@c-morten That did it, thanks!  Using the right animation path fixed my "lost in space" problem with the Host positioning.  I'm good to go now.

- Do you know where I can find a complete list of all the _emotes_ and all the _gestures_ for each character?

BTW, I can't shake the feeling that the animations in _Sumerian-Hosts/ThreeJS_ are smoother than in the _Sumerian_ canvas environment.  Also, the shading of the characters and the ambient lighting seems more pleasing and easier on the eye.  Have you found that to be true too?

**Comment by c-morten** [comment]
The emotes and gestures can be found inside the emote and gesture glb files, one way to see what animations they contain would be to import them into a program like Blender. If you're looking for a scripted solution, you can use the AnimationFeature's [getAnimations ](https://aws-samples.github.io/amazon-sumerian-hosts/core_AnimationFeature.html#getAnimations) method. This will return an array of the names of all animations on a given layer. To see an example, take a look inside the toggleHost method in the example file. We use that method to populate the emote selector dropdown depending on which host tab is active.

As for the host looking a little different than they do inside Sumerian, this is because we provided the host assets as glTF, which is a file format that supports PBR materials. That shading model gives much better results than the standard materials inside Sumerian. We do have support for PBR in Sumerian now but updating the host assets is not a priority at the moment. For the animation looking smoother, I can only speculate. I know that we only support linear interpolation between keyframes in Sumerian and three.js and Babylon.js both support cubic spline, it's also possible the framerates are a bit better.

**Comment by roschler** [comment]
@c-morten Thanks!

**Comment by roschler** [comment]
"This will return an array of the names of all animations on a given layer. To see an example, take a look inside the toggleHost method in the example file. We use that method to populate the emote selector dropdown depending on which host tab is active."

@c-morten Ok, got it.  I was hoping there were more _emotes_ available for the **Alien** character than the singular _angry_.  So I can just use the mini-UI on the _three.html_ to explore all the _emotes_ right?  

Where would I go to hire someone to build new animations, but just for the existing characters in the distribution assets?  I looked at Mixamo as you suggested and I didn't see a "freelancer" section, and most of the existing animations are not really great for the **Alien** character.

**Comment by c-morten** [comment]
The Alien character was more of a test to prove out that the host functionality can still work on other rigs with different proportions and joint orientations, so we didn't finish out the full set of animations the other hosts contain. I'm not really sure of the best place to go for hiring a freelance animator but you might try a site like cgsociety, it looks like they do have a forum board for recruiting: https://forums.cgsociety.org/c/help/recruitment.
