### ISSUE TITLE
List of embedded SSML feature strings?

### ISSUE THREAD

**Issue by roschler** [aws-samples/amazon-sumerian-hosts#19]
Where can I find the complete list of embedded SSML feature strings?  For example, like this one used to adjust the look-at target during speech:
```
mark(name='{"feature":"PointOfInterestFeature","method":"setTargetByName","args":["chargaze"]}')
```

**Comment by c-morten** [comment]
We currently support this syntax on the [GestureFeature ](https://aws-samples.github.io/amazon-sumerian-hosts/GestureFeature.html)and [PointOfInterestFeature](https://aws-samples.github.io/amazon-sumerian-hosts/core_PointOfInterestFeature.html). You can use it with any of the methods on those features whose arguments can be parsed from a JSON string. We could easily extend this functionality to the [LipsyncFeature ](https://aws-samples.github.io/amazon-sumerian-hosts/core_LipsyncFeature.html)and [AnimationFeature ](https://aws-samples.github.io/amazon-sumerian-hosts/core_AnimationFeature.html)if it there's demand for it, please let us know if you would find this useful in your projects.

**Comment by roschler** [comment]
@c-morten Thanks!  Is there something that documents the embedded string syntax?  For example, what does "chargaze" actually mean and how you specify a target (specific object or host) with that syntax?

**Comment by c-morten** [comment]
"chargaze" is the name of a joint (so an Object3D) in the alien's glTF character file, it's located directly between the eyes. If you open a glTF file in a program like Blender you can inspect the names and locations of all of the joints in the skeleton. If you do this, you'll notice that there is a ':' separating 'char' and 'gaze'. Three.js strips the ':' from names on import, which is why we have removed it here. [setTargetByName ](https://aws-samples.github.io/amazon-sumerian-hosts/core_PointOfInterestFeature.html#setTargetByName)allows you to specify the name of any Object3D in the scene that you want the host to look at, it will search the scene for that name and find the corresponding object.

**Comment by roschler** [comment]
@c-morten What happens if you specify a target that exists in more than one host?  For example, suppose there were two alien characters on screen, I'm assuming they would both have a "chargaze" joint?

**Comment by c-morten** [comment]
We do have a `setTargetById` method as well. This allows you to pass an object's [id](https://threejs.org/docs/#api/en/core/Object3D.id) property, which is unique. For that you'd probably need to use string formatting to insert the id after the characters are imported since id gets generated when the object is created.

Another alternative would be to create your own message for the name of the mark tag and add a listener for that. Then you could use whatever logic you'd like to figure out which host you want to target inside your listener function.

**Comment by roschler** [comment]
@c-morten Thanks. Side questions, is there a quick way to get rid of all the "stray hair" on the Cristine model?  Hopefully some way  that someone who is not an animator (massive understatement in my case) could do?  I use the models frequently with their head position in profile and those hair elements look really bad from that view on that model.

**Comment by c-morten** [comment]
The only way to do that would be to edit the hair geometry in an external program like Blender, which would take some modeling and rigging knowledge. You would need to detach the skinning, make your geometry edits and then re-skin. You'd likely need to make some texture updates as well since the hair was textured with that specific geometry in mind.

**Comment by roschler** [comment]
"We could easily extend this functionality to the LipsyncFeature and AnimationFeature if it there's demand for it, please let us know if you would find this useful in your projects."

I would definitely find that useful.  Should I post that as a separate issue?

**Comment by c-morten** [comment]
^ Please do post a separate issue for this, I'll mark it as a feature request and add it to the backlog
