### ISSUE TITLE
Are these sub-gestures?

### ISSUE THREAD

**Issue by roschler** [aws-samples/amazon-sumerian-hosts#21]
Looking at the `gestures.json` file I see entries like this:
```
{
  "aggressive": {
    "queueOptions": [
      {
        "name": "in",
        "from": 0,
        "to": 43,
        "loopCount": 1
      },
      {
        "name": "hold",
        "from": 43,
        "to": 90
      },
      {
        "name": "out",
        "from": 90,
        "to": 158,
        "loopCount": 1
      }
    ]
  }
```
Currently I have only been using the gestures using the top level property name (e.g. - "aggressive"):
```
host.GestureFeature.playGesture('Gesture', 'aggressive');
```
Given the JSON block above, am I underutlizing the gestures library?  Can I pass a dotted string and get access to what I'm calling the "sub-gestures" too (e.g. - "in", "hold", "out")?  For example:
```
host.GestureFeature.playGesture('Gesture', 'aggressive.hold');
```
If not, then what is the purpose of the child elements like "in", "hold", "out"?  If I can, then is my syntax correct and do the emotes similarly have sub-emotes?

**Comment by c-morten** [comment]
For the gesture animations we provide in gesture.glb, we created the animations with a loop-able segment in the middle of each clip where the host is in the full posture of the gesture. The config options serve 2 purposes - first they provide the start and end frames to be able to split each clip so we can extract that looping hold. The other purpose is to configure a specific animation type called a [QueueState](https://aws-samples.github.io/amazon-sumerian-hosts/QueueState.html). This type of animation allows you to define N-number of sub-animations. When a QueueState animation is played, it will play each sub-animation in sequence until it reaches the end of its animation queue or is interrupted by a different animation. The queue will automatically advance for animations that do not loop infinitely. Because of this, we have a 'holdTime' parameter in the GestureFeature that allows you to specify how many seconds a QueueState gesture animation will stay in an infinitely looping sub-animation before the GestureFeature advances the QueueState to the next sub-animation. You are not required to use QueueStates for gestures, it is completely optional. We demonstrate this with the emote animations, which are just regular [SingleState](https://aws-samples.github.io/amazon-sumerian-hosts/core_SingleState.html) animations. We do not support executing sub-animations manually. However if you wanted to force a QueueState to progress to the next sub-animation while it is playing you can use [AnimationFeature.playNextAnimation](https://aws-samples.github.io/amazon-sumerian-hosts/core_AnimationFeature.html#playNextAnimation).

**Comment by roschler** [comment]
@c-morten Thanks.
