### ISSUE TITLE
Display the character without animations

### ISSUE THREAD

**Issue by DC2009** [aws-samples/amazon-sumerian-hosts#23]
I want to display just the character, without any animations.
In `babylon.html` I commented out all the code responsible for loading the animations in the function `createHost`.
So basically just this line is left
`const host = new HOST.HostObject({owner: character});`
and the host is returned.
The character appears for a very short moment, probably during/after `loadCharacter` and then disappears.
Is it possible to show the character only?

**Comment by c-morten** [comment]
Hi @DC2009. Which host asset are you using? The default behavior of the `BABYLON.SceneLoader.LoadAssetContainerAsync` method which we use in our example is to automatically play the animation contained in the file being loaded. For all host assets we provide in our repository other than Wes and Fiona, we have a single animation in the character glTF file called `bindPoseOffset`. The purpose of this animation is to be played additively on top of all other animations so that the animations we exported from the Wes and Fiona rigs can be shared across all male and female hosts. Inside the `loadCharacter` method, you'll seeing following line that converts that animation to additive format: `BABYLON.AnimationGroup.MakeAnimationAdditive(bindPoseOffset);`. Since you're commenting out all of the host code, this line will result in an additive format animation being played as override, which would result in the host disappearing since the scale values would be set to (0,0,0). You don't actually want that animation to play anyway since you're trying to avoid playing animations, so try replacing that line with the following: `bindPoseOffset.stop();`

**Comment by DC2009** [comment]
Hi @c-morten. Thanks for your quick answer. Your solution worked perfectly! I tested only Grace. I missed that line as I concentrated on the `createHost` function...
