### ISSUE TITLE
How to sync Lex response with gesture to Sumerian Host 

### ISSUE THREAD

**Issue by KISSMonX** [aws-samples/amazon-sumerian-hosts#33]
We are working on BabylonJS that integrates Sumerian Host. By calling Lex we received audio and message, how to sync Lex respond message with Sumerian host so that Host can play both audio and gesture. This could leave out the Polly and only need Lex. Is this possible? 
Thanks.

**Comment by c-morten** [comment]
Hi @KISSMonX. We do not currently have the capability of providing audio to the TextToSpeechFeature. This is because a speechmark stream is required as well and must be generated from the same source as the audio in order for the messages to sync up and allow the lipsync and gestures to happen in time with the audio. Unfortunately Lex is not capable of generating speechmark data so there's really no way around using Polly if you want lipsync and gestures. You could however execute TextToSpeechFeature.play using the response message you receive from Lex. Hope this helps.
