### ISSUE TITLE
Google Canary - Error: net::ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY

### ISSUE THREAD

**Issue by IvanFarkas** [aws-samples/amazon-sumerian-hosts#45]
### Google Canary - Error: net::ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY

By following the [Using the Dialogue Component and Amazon Lex to Build a Chatbot](https://docs.sumerian.amazonaws.com/tutorials/create/beginner/dialogue-component/) tutorial I made a new chatbot scene.
I use Windows 10 Pro (version 2004)
Using Google Chrome (Version 90.0.4430.93 (Official Build) (64-bit)) it's all good, working OK.

Using Google Chrome Canary (Version 92.0.4495.0 (Official Build) canary (64-bit)) I am experiencing errors.
This is important to fix since Canary code will make its way to standard Crome soon!

```
aws-sdk-2.657.0.min.js:71 POST https://runtime.lex.us-east-1.amazonaws.com/bot/BookTrip/alias/Test/user/us-east-1%3A350bd97c-3c63-47ad-8b99-eeceffda7c83/content net::ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY
```
![Canary_error](https://user-images.githubusercontent.com/11818001/116832340-c2f70980-ab82-11eb-8ffe-e4e74834425d.png)

**Comment by jkerste** [comment]
Thanks for reporting this @IvanFarkas. We were able to reproduce this for a while and were tracking down the cause, however we are no longer able to reproduce this on Chrome 92.0.4515.59.

Can you confirm whether or not this issue is still occurring for you on Chrome v92? That version is currently in the Chrome Beta release channel.

**Comment by IvanFarkas** [comment]
OK on Version 93.0.4555.0 (Official Build) canary (64-bit).
